//控制过滤时是否限制蛋白长度
function changelen(){
	var iflen = document.getElementById("iflen")
	var l1 = iflen.options[iflen.selectedIndex].value
	var t = iflen.parentNode
	if (l1 == 'y'){
		var inlen = document.createElement("input")
		var b = document.createElement("br")
		var te = document.createTextNode("蛋白长度大于等于")
		var te2 = document.createTextNode("AA")
		inlen.setAttribute("value", "300")
		inlen.setAttribute("size", "5")
		inlen.setAttribute("TYPE", "TEXT")
		inlen.setAttribute("id", "maxlen")
		t.insertBefore(b, iflen.nextSibling)
		t.insertBefore(te, b.nextSibling)
		t.insertBefore(inlen, te.nextSibling)
		t.insertBefore(te2, inlen.nextSibling)
	}
	if (l1 == 'n'){
		t.removeChild(t.lastChild)
		t.removeChild(t.lastChild)
		t.removeChild(t.lastChild)
		t.removeChild(t.lastChild)
	}
}

//控制过滤时是否限制氨基酸种类
function changeaa(){
	var ifaa = document.getElementById("ifaa")
	var l1 = ifaa.options[ifaa.selectedIndex].value
	var t = ifaa.parentNode
	if (l1 == 'y'){
		var intype = document.createElement("select")
		intype.setAttribute("id", "aatype")
		var inaa = document.createElement("input")
		var te = document.createTextNode("含量大于等于")
		var b = document.createElement("br")
		inaa.setAttribute("value", "0.1")
		inaa.setAttribute("TYPE", "TEXT")
		inaa.setAttribute("size", "5")
		inaa.setAttribute("id", "maxaa")
		var myOption1=document.createElement("option")
		myOption1.setAttribute("value","A")
		myOption1.appendChild(document.createTextNode("A"))
		var myOption2=document.createElement("option")
		myOption2.setAttribute("value","V")
		myOption2.appendChild(document.createTextNode("V"))
		var myOption3=document.createElement("option")
		myOption3.setAttribute("value","L")
		myOption3.appendChild(document.createTextNode("L"))
		var myOption4=document.createElement("option")
		myOption4.setAttribute("value","I")
		myOption4.appendChild(document.createTextNode("I"))
		var myOption5=document.createElement("option")
		myOption5.setAttribute("value","F")
		myOption5.appendChild(document.createTextNode("F"))
		var myOption6=document.createElement("option")
		myOption6.setAttribute("value","W")
		myOption6.appendChild(document.createTextNode("W"))
		var myOption7=document.createElement("option")
		myOption7.setAttribute("value","M")
		myOption7.appendChild(document.createTextNode("M"))
		var myOption8=document.createElement("option")
		myOption8.setAttribute("value","P")
		myOption8.appendChild(document.createTextNode("P"))
		var myOption9=document.createElement("option")
		myOption9.setAttribute("value","G")
		myOption9.appendChild(document.createTextNode("G"))
		var myOption10=document.createElement("option")
		myOption10.setAttribute("value","S")
		myOption10.appendChild(document.createTextNode("S"))
		var myOption11=document.createElement("option")
		myOption11.setAttribute("value","T")
		myOption11.appendChild(document.createTextNode("T"))
		var myOption12=document.createElement("option")
		myOption12.setAttribute("value","C")
		myOption12.appendChild(document.createTextNode("C"))
		var myOption13=document.createElement("option")
		myOption13.setAttribute("value","Y")
		myOption13.appendChild(document.createTextNode("Y"))
		var myOption14=document.createElement("option")
		myOption14.setAttribute("value","N")
		myOption14.appendChild(document.createTextNode("N"))
		var myOption15=document.createElement("option")
		myOption15.setAttribute("value","Q")
		myOption15.appendChild(document.createTextNode("Q"))
		var myOption16=document.createElement("option")
		myOption16.setAttribute("value","H")
		myOption16.appendChild(document.createTextNode("H"))
		var myOption17=document.createElement("option")
		myOption17.setAttribute("value","K")
		myOption17.appendChild(document.createTextNode("K"))
		var myOption18=document.createElement("option")
		myOption18.setAttribute("value","R")
		myOption18.appendChild(document.createTextNode("R"))
		var myOption19=document.createElement("option")
		myOption19.setAttribute("value","D")
		myOption19.appendChild(document.createTextNode("D"))
		var myOption20=document.createElement("option")
		myOption20.setAttribute("value","E")
		myOption20.appendChild(document.createTextNode("E"))
		intype.appendChild(myOption1)
		intype.appendChild(myOption2)
		intype.appendChild(myOption3)
		intype.appendChild(myOption4)
		intype.appendChild(myOption5)
		intype.appendChild(myOption6)
		intype.appendChild(myOption7)
		intype.appendChild(myOption8)
		intype.appendChild(myOption9)
		intype.appendChild(myOption10)
		intype.appendChild(myOption11)
		intype.appendChild(myOption12)
		intype.appendChild(myOption13)
		intype.appendChild(myOption14)
		intype.appendChild(myOption15)
		intype.appendChild(myOption16)
		intype.appendChild(myOption17)
		intype.appendChild(myOption18)
		intype.appendChild(myOption19)
		intype.appendChild(myOption20)
		t.insertBefore(b, ifaa.nextSibling)
		t.insertBefore(intype, b.nextSibling)
		t.insertBefore(te, intype.nextSibling)
		t.insertBefore(inaa, te.nextSibling)
	}
	if (l1 == 'n'){
		t.removeChild(t.lastChild)
		t.removeChild(t.lastChild)
		t.removeChild(t.lastChild)
		t.removeChild(t.lastChild)
	}
}


//控制过滤时是否限制表达情况
function changeexp(){
	var sp1 = document.getElementById("spname")
	var sp = sp1.options[sp1.selectedIndex].value
	var ifexp = document.getElementById("ifexp")
	var l1 = ifexp.options[ifexp.selectedIndex].value
	var t = ifexp.parentNode
	if (t.childNodes.length > 3){
		t.removeChild(t.lastChild)
		t.removeChild(t.lastChild)
		t.removeChild(t.lastChild)
		t.removeChild(t.lastChild)
		t.removeChild(t.lastChild)
	}
	if (l1 == 'y'){
		var instage = document.createElement("select")
		var intype = document.createElement("select")
		intype.setAttribute("onchange", "changeexp2()")
		intype.setAttribute("id", "ifexp2")
		instage.setAttribute("id", "ifexp1")
		var b = document.createElement("br")
		var te = document.createTextNode("在")
		var te2 = document.createTextNode("阶段")
		if (sp == "BBA"){
			var myOption1=document.createElement("option")
			myOption1.setAttribute("value","blood")
			myOption1.appendChild(document.createTextNode("血淋巴"))
			var myOption2=document.createElement("option")
			myOption2.setAttribute("value","wing")
			myOption2.appendChild(document.createTextNode("棉铃虫翅"))
			var myOption3=document.createElement("option")
			myOption3.setAttribute("value","root")
			myOption3.appendChild(document.createTextNode("根际"))
			instage.appendChild(myOption1)
			instage.appendChild(myOption2)
			instage.appendChild(myOption3)
			var myOption1=document.createElement("option")
			myOption1.setAttribute("value","y")
			myOption1.appendChild(document.createTextNode("有表达"))
			var myOption2=document.createElement("option")
			myOption2.setAttribute("value","high")
			myOption2.appendChild(document.createTextNode("特异高表达"))
			intype.appendChild(myOption1)
			intype.appendChild(myOption2)
			t.insertBefore(b, ifexp.nextSibling)
			t.insertBefore(te, b.nextSibling)
			t.insertBefore(instage, te.nextSibling)
			t.insertBefore(te2, instage.nextSibling)
			t.insertBefore(intype, te2.nextSibling)		
		}
		else if (sp == "MAA"){
			var myOption1=document.createElement("option")
			myOption1.setAttribute("value","blood")
			myOption1.appendChild(document.createTextNode("血淋巴"))
			var myOption2=document.createElement("option")
			myOption2.setAttribute("value","wing")
			myOption2.appendChild(document.createTextNode("蝗虫翅"))
			var myOption3=document.createElement("option")
			myOption3.setAttribute("value","root")
			myOption3.appendChild(document.createTextNode("孢子"))
			instage.appendChild(myOption1)
			instage.appendChild(myOption2)
			instage.appendChild(myOption3)
			var myOption1=document.createElement("option")
			myOption1.setAttribute("value","y")
			myOption1.appendChild(document.createTextNode("有表达"))
			var myOption2=document.createElement("option")
			myOption2.setAttribute("value","high")
			myOption2.appendChild(document.createTextNode("特异高表达"))
			intype.appendChild(myOption1)
			intype.appendChild(myOption2)
			t.insertBefore(b, ifexp.nextSibling)
			t.insertBefore(te, b.nextSibling)
			t.insertBefore(instage, te.nextSibling)
			t.insertBefore(te2, instage.nextSibling)
			t.insertBefore(intype, te2.nextSibling)		
		}
		else {
			alert('尚无此物种表达信息')
		}
	}
}

function changeexp2(){
	var ifexp2 = document.getElementById("ifexp2")
	var l1 = ifexp2.options[ifexp2.selectedIndex].value
	var t = ifexp2.parentNode
	if (l1 == 'high'){
		var inexp2 = document.createElement("input")
		var te = document.createTextNode("倍以上")
		inexp2.setAttribute("value", "2")
		inexp2.setAttribute("size", "5")
		inexp2.setAttribute("TYPE", "TEXT")
		inexp2.setAttribute("id", "ifexp3")
		t.insertBefore(inexp2, ifexp2.nextSibling)
		t.insertBefore(te, inexp2.nextSibling)
	}
	if (l1 == 'y'){
			t.removeChild(t.lastChild)
			t.removeChild(t.lastChild)
			t.removeChild(t.lastChild)
	}
}